name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.template"
      - "rootfs/**"

env:
  DOCKER_BUILDKIT: 1
  COSIGN_EXPERIMENTAL: 1

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  php80-arm64:
    name: 8.0 on ARM64
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
  
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/friendsofshopware/production-docker-base:8.0-arm64,ghcr.io/friendsofshopware/production-docker-base:8.0.28-arm64
          context: "8.0"
          cache-from: type=gha,scope=php8.0
          cache-to: type=gha,mode=max,scope=php8.0
          push: true

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.0.28-arm64

  php80-amd64:
      name: 8.0 on AMD64
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - uses: docker/build-push-action@v4
          with:
            tags: ghcr.io/friendsofshopware/production-docker-base:8.0-amd64,ghcr.io/friendsofshopware/production-docker-base:8.0.28-amd64
            context: "8.0"
            cache-from: type=gha,scope=php8.0
            cache-to: type=gha,mode=max,scope=php8.0
            push: true

        - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.0.28-amd64
  
  php81-arm64:
    name: 8.1 on ARM64
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
  
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/friendsofshopware/production-docker-base:8.1-arm64,ghcr.io/friendsofshopware/production-docker-base:8.1.19-arm64
          context: "8.1"
          cache-from: type=gha,scope=php8.1
          cache-to: type=gha,mode=max,scope=php8.1
          push: true

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.1.19-arm64

  php81-amd64:
      name: 8.1 on AMD64
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - uses: docker/build-push-action@v4
          with:
            tags: ghcr.io/friendsofshopware/production-docker-base:8.1-amd64,ghcr.io/friendsofshopware/production-docker-base:8.1.19-amd64
            context: "8.1"
            cache-from: type=gha,scope=php8.1
            cache-to: type=gha,mode=max,scope=php8.1
            push: true

        - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.1.19-amd64
  
  php82-arm64:
    name: 8.2 on ARM64
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
  
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/friendsofshopware/production-docker-base:8.2-arm64,ghcr.io/friendsofshopware/production-docker-base:8.2.6-arm64
          context: "8.2"
          cache-from: type=gha,scope=php8.2
          cache-to: type=gha,mode=max,scope=php8.2
          push: true

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.2.6-arm64

  php82-amd64:
      name: 8.2 on AMD64
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3
  
        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
  
        - uses: docker/build-push-action@v4
          with:
            tags: ghcr.io/friendsofshopware/production-docker-base:8.2-amd64,ghcr.io/friendsofshopware/production-docker-base:8.2.6-amd64
            context: "8.2"
            cache-from: type=gha,scope=php8.2
            cache-to: type=gha,mode=max,scope=php8.2
            push: true

        - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.2.6-amd64
  

  merge-manifest:
    name: Merge Manifest
    runs-on: ubuntu-22.04
    needs:
      - php80-arm64
      - php80-amd64
      - php81-arm64
      - php81-amd64
      - php82-arm64
      - php82-amd64

    steps:
      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - run: docker manifest create ghcr.io/friendsofshopware/production-docker-base:8.0 --amend ghcr.io/friendsofshopware/production-docker-base:8.0.28-amd64 --amend ghcr.io/friendsofshopware/production-docker-base:8.0.28-arm64

      - run: docker manifest create ghcr.io/friendsofshopware/production-docker-base:8.0.28 --amend ghcr.io/friendsofshopware/production-docker-base:8.0.28-amd64 --amend ghcr.io/friendsofshopware/production-docker-base:8.0.28-arm64

      - run: docker manifest push ghcr.io/friendsofshopware/production-docker-base:8.0

      - run: docker manifest push ghcr.io/friendsofshopware/production-docker-base:8.0.28

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.0

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.0.28

      - run: docker manifest create ghcr.io/friendsofshopware/production-docker-base:8.1 --amend ghcr.io/friendsofshopware/production-docker-base:8.1.19-amd64 --amend ghcr.io/friendsofshopware/production-docker-base:8.1.19-arm64

      - run: docker manifest create ghcr.io/friendsofshopware/production-docker-base:8.1.19 --amend ghcr.io/friendsofshopware/production-docker-base:8.1.19-amd64 --amend ghcr.io/friendsofshopware/production-docker-base:8.1.19-arm64

      - run: docker manifest push ghcr.io/friendsofshopware/production-docker-base:8.1

      - run: docker manifest push ghcr.io/friendsofshopware/production-docker-base:8.1.19

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.1

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.1.19

      - run: docker manifest create ghcr.io/friendsofshopware/production-docker-base:8.2 --amend ghcr.io/friendsofshopware/production-docker-base:8.2.6-amd64 --amend ghcr.io/friendsofshopware/production-docker-base:8.2.6-arm64

      - run: docker manifest create ghcr.io/friendsofshopware/production-docker-base:8.2.6 --amend ghcr.io/friendsofshopware/production-docker-base:8.2.6-amd64 --amend ghcr.io/friendsofshopware/production-docker-base:8.2.6-arm64

      - run: docker manifest push ghcr.io/friendsofshopware/production-docker-base:8.2

      - run: docker manifest push ghcr.io/friendsofshopware/production-docker-base:8.2.6

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.2

      - run: cosign sign --yes ghcr.io/friendsofshopware/production-docker-base:8.2.6

